module.exports = {
	cards: [
		{
			artist: 'Jim Nelson',
			cardClass: 'PRIEST',
			collectible: true,
			cost: 0,
			dbfId: 48976,
			flavor: '"Help! I\'ve fallen and I can\'t get down!"',
			id: 'BOT_517',
			name: 'Topsy Turvy',
			playRequirements: {
				REQ_MINION_TARGET: 0,
				REQ_TARGET_TO_PLAY: 0
			},
			rarity: 'COMMON',
			set: 'BOOMSDAY',
			text: "Swap a minion's Attack and Health.",
			type: 'SPELL',
			quantity: 2
		},
		{
			artist: 'Jessica Jung',
			cardClass: 'PRIEST',
			collectible: true,
			cost: 1,
			dbfId: 613,
			flavor:
				'Sure the extra protection is nice, but the shield really reduces visibility.',
			howToEarn: 'Unlocked at Level 1.',
			howToEarnGolden: 'Unlocked at Level 47.',
			id: 'CS2_004',
			name: 'Power Word: Shield',
			playRequirements: {
				REQ_MINION_TARGET: 0,
				REQ_TARGET_TO_PLAY: 0
			},
			rarity: 'FREE',
			set: 'CORE',
			text: 'Give a minion +2 Health.\nDraw a card.',
			type: 'SPELL',
			quantity: 2
		},
		{
			artist: 'Howard Lyon',
			attack: 1,
			cardClass: 'NEUTRAL',
			collectible: true,
			cost: 1,
			dbfId: 648,
			flavor: 'This card is boaring.',
			health: 1,
			howToEarnGolden: 'Unlocked at Hunter Level 53.',
			id: 'CS2_171',
			mechanics: ['CHARGE'],
			name: 'Stonetusk Boar',
			race: 'BEAST',
			rarity: 'FREE',
			set: 'CORE',
			text: '<b>Charge</b>',
			type: 'MINION',
			quantity: 2
		},
		{
			artist: 'Terese Nielsen',
			attack: 1,
			cardClass: 'PRIEST',
			collectible: true,
			cost: 1,
			dbfId: 1650,
			flavor:
				'They help the downtrodden and distressed.  Also they sell cookies.',
			health: 3,
			howToEarn: 'Unlocked at Level 1.',
			howToEarnGolden: 'Unlocked at Level 40.',
			id: 'CS2_235',
			mechanics: ['TRIGGER_VISUAL'],
			name: 'Northshire Cleric',
			rarity: 'FREE',
			set: 'CORE',
			text: 'Whenever a minion is healed, draw a card.',
			type: 'MINION',
			quantity: 2
		},
		{
			artist: 'Jim Pavelec',
			cardClass: 'PRIEST',
			collectible: true,
			cost: 2,
			dbfId: 1361,
			flavor: 'Double the trouble. Double the fun!',
			howToEarn: 'Unlocked at Level 2.',
			howToEarnGolden: 'Unlocked at Level 28.',
			id: 'CS2_236',
			name: 'Divine Spirit',
			playRequirements: {
				REQ_MINION_TARGET: 0,
				REQ_TARGET_TO_PLAY: 0
			},
			rarity: 'FREE',
			set: 'CORE',
			text: "Double a minion's Health.",
			type: 'SPELL',
			quantity: 2
		},
		{
			artist: 'Zoltan Boros',
			attack: 2,
			cardClass: 'PRIEST',
			collectible: true,
			cost: 5,
			dbfId: 51714,
			flavor: 'It’s always nice to steal a familiar face.',
			health: 6,
			id: 'DAL_039',
			mechanics: ['DEATHRATTLE', 'TAUNT'],
			name: 'Convincing Infiltrator',
			rarity: 'RARE',
			set: 'DALARAN',
			text:
				'[x]<b><b>Taunt</b></b>\n<b>Deathrattle:</b> Destroy a\n random enemy minion.',
			type: 'MINION',
			quantity: 2
		},
		{
			artist: 'J. Axer',
			cardClass: 'PRIEST',
			collectible: true,
			cost: 0,
			dbfId: 52632,
			flavor: 'Please confirm your age before reading this flavor text.',
			id: 'DAL_723',
			name: 'Forbidden Words',
			playRequirements: {
				REQ_MINION_TARGET: 0,
				REQ_TARGET_TO_PLAY: 0
			},
			rarity: 'RARE',
			set: 'DALARAN',
			text:
				'[x]Spend all your Mana.\nDestroy a minion with that\nmuch Attack or less.',
			type: 'SPELL',
			quantity: 2
		},
		{
			artist: 'Dave Kendall',
			attack: 1,
			cardClass: 'NEUTRAL',
			collectible: true,
			cost: 3,
			dbfId: 1659,
			flavor:
				'He trained when he was younger to be an acolyte of joy, but things didn’t work out like he thought they would.',
			health: 3,
			id: 'EX1_007',
			mechanics: ['TRIGGER_VISUAL'],
			name: 'Acolyte of Pain',
			rarity: 'COMMON',
			set: 'EXPERT1',
			text: 'Whenever this minion takes damage, draw a card.',
			type: 'MINION',
			quantity: 2
		},
		{
			artist: 'Zoltan & Gabor',
			cardClass: 'PRIEST',
			collectible: true,
			cost: 0,
			dbfId: 1189,
			flavor:
				'Reserved for enemy spellcasters, evil liches from beyond the grave, and karaoke nights at the Grim Guzzler.',
			id: 'EX1_332',
			mechanics: ['SILENCE'],
			name: 'Silence',
			playRequirements: {
				REQ_MINION_TARGET: 0,
				REQ_TARGET_TO_PLAY: 0
			},
			rarity: 'COMMON',
			set: 'EXPERT1',
			text: '<b>Silence</b> a minion.',
			type: 'SPELL',
			quantity: 1
		},
		{
			artist: 'Sean O’Daniels',
			cardClass: 'PRIEST',
			collectible: true,
			cost: 4,
			dbfId: 1366,
			flavor: 'It dispels buffs, powers, hopes, and dreams.',
			id: 'EX1_626',
			mechanics: ['SILENCE'],
			name: 'Mass Dispel',
			rarity: 'RARE',
			set: 'EXPERT1',
			text: '<b>Silence</b> all enemy minions. Draw a card.',
			type: 'SPELL',
			quantity: 2
		},
		{
			artist: 'Alex Horley Orlandelli',
			attack: 3,
			cardClass: 'NEUTRAL',
			collectible: true,
			cost: 2,
			dbfId: 1014,
			flavor: 'BOOM BABY BOOM!  BAD IS GOOD!  DOWN WITH GOVERNMENT!',
			health: 2,
			id: 'NEW1_020',
			mechanics: ['TRIGGER_VISUAL'],
			name: 'Wild Pyromancer',
			rarity: 'RARE',
			set: 'EXPERT1',
			text: 'After you cast a spell, deal 1 damage to ALL minions.',
			type: 'MINION',
			quantity: 2
		},
		{
			artist: 'Vladimir Kafanov',
			cardClass: 'PRIEST',
			collectible: true,
			cost: 5,
			dbfId: 50071,
			flavor: 'Black Friday gets worse every year.',
			id: 'TRL_258',
			name: 'Mass Hysteria',
			playRequirements: {
				REQ_ENEMY_TARGET: 0,
				REQ_MINION_TARGET: 0
			},
			rarity: 'RARE',
			set: 'TROLL',
			text: 'Force each minion to attack another random minion.',
			type: 'SPELL',
			quantity: 2
		},
		{
			artist: 'James Ryman',
			attack: 2,
			cardClass: 'PRIEST',
			collectible: true,
			cost: 4,
			dbfId: 53929,
			elite: true,
			flavor:
				'All minions are equal, but some minions are more equal than others.',
			health: 7,
			id: 'ULD_262',
			mechanics: ['TRIGGER_VISUAL'],
			name: 'High Priest Amet',
			rarity: 'LEGENDARY',
			set: 'ULDUM',
			text:
				"[x]Whenever you summon a\nminion, set its Health equal\nto this minion's.",
			type: 'MINION',
			quantity: 1
		},
		{
			artist: 'Jim Nelson',
			attack: 3,
			cardClass: 'PRIEST',
			collectible: true,
			cost: 4,
			dbfId: 53935,
			flavor: '"Come with me if you want to re-live."',
			health: 1,
			id: 'ULD_268',
			mechanics: ['BATTLECRY'],
			name: 'Psychopomp',
			rarity: 'EPIC',
			referencedTags: ['REBORN'],
			set: 'ULDUM',
			text:
				'[x]<b>Battlecry:</b> Summon a\nrandom friendly minion\nthat died this game.\nGive it <b>Reborn</b>.',
			type: 'MINION',
			quantity: 2
		},
		{
			artist: 'Zoltan Boros',
			cardClass: 'PRIEST',
			collectible: true,
			cost: 9,
			dbfId: 54431,
			flavor:
				"Don't worry, there's a happy little funhouse right under that sand pit.",
			id: 'ULD_718',
			mechanics: ['SILENCE'],
			name: 'Plague of Death',
			rarity: 'EPIC',
			set: 'ULDUM',
			text: '<b>Silence</b> and destroy all minions.',
			type: 'SPELL',
			quantity: 2
		}
	],
	hero: {
		cardClass: 'PRIEST',
		collectible: true,
		dbfId: 813,
		health: 30,
		id: 'HERO_09',
		name: 'Anduin Wrynn',
		rarity: 'FREE',
		set: 'CORE',
		type: 'HERO'
	}
}
